name: Add features via Pull Request
description: Add an idea for this project
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      ## Use this form if you wan't to add a feature to TNT and Disparity Mod.
      **Note: This Pull Request will be added to a specific milestone before being added to our mod.**
- type: textarea
  attributes:
    label: Feature
    description: What do feature will you add for TNT and Disparity mod?
  validations:
    required: true
- type: textarea
  attributes:
    label: Benefit
    description: Is your/our benefit for this feature you want to add?
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Check the following if you have followed.
    options:
    - label: I have searched the issue tracker and did not find an issue suggesting my idea.
      required: true
    - label: I read the [Code of Conduct](https://github.com/Team-Burnuts/BurnutsPlusTNTandDisparityMod/blob/master/CODE_OF_CONDUCT.md) and pledged to follow it.
      required: true
    - label: I read the [Contributing Guidelines](https://github.com/Team-Burnuts/BurnutsPlusTNTandDisparityMod/blob/master/CONTRIBUTING.md) and pledged to follow it.
      required: true
    - label: I used [MCreator](https://mcreator.net/download) to add this feature.
      required: true
    - label: Me and my commiters signed the [Burnuts CLA](https://cla-assistant.io/Team-Burnuts/BurnutsPlusTNTandDisparityMod).
      required: true
