# Gradle
- task: VSTest@2
  inputs:
    testSelector: 'testRun'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    distributionBatchType: 'basedOnAssembly'
    dontDistribute: true
    failOnMinTestsNotRun: false

trigger:
- master

pool:
  vmImage: ubuntu-latest
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx4096m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
