modLoader="javafml"
loaderVersion="[37,)"
license="GNU Lesser General Public License version 2.1 (LGPLv2.1)"

[[mods]]
modId="tnt_and_disparity"
version="0.4.1alpha-build.0703-integrationtest"
displayName="TNT and Disparity"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
updateJSONURL="https://raw.githubusercontent.com/Team-Burnuts/BurnutsPlusTNTandDisparityMod/master/update.json"
logoFile="logo.png"
authors="Team Burnuts, MCreator"
description='''
You landed in a world that is more than you expect.
'''

[[dependencies.tnt_and_disparity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.tnt_and_disparity]]
    modId="twilightforest"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tnt_and_disparity]]
    modId="twilightforest-1.17"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

