modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="tnt_and_disparity"
version="0.3.1alpha-build.0218"
displayName="TNT and Disparity"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Burnuts Gaming, MCreator"

[[dependencies.tnt_and_disparity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




