modLoader="javafml"
loaderVersion="[36,)"
license="GNU Lesser General Public License version 2.1 (LGPLv2.1)"

[[mods]]
modId="tnt_and_disparity"
version="0.4.1alpha-build.0615"
displayName="TNT and Disparity"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
updateJSONURL="https://raw.githubusercontent.com/Team-Burnuts/BurnutsPlusTNTandDisparityMod/master/update.json"
logoFile="logo.png"
authors="Burnuts Gaming, MCreator"
description='''
You landed in a world that is more than you expect.
'''

[[dependencies.tnt_and_disparity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"


[[dependencies.tnt_and_disparity]]
    modId="twilightforest"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tnt_and_disparity]]
    modId="just_enough_items"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tnt_and_disparity]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tnt_and_disparity]]
    modId="curios"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tnt_and_disparity]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tnt_and_disparity]]
    modId="twilightforest"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tnt_and_disparity]]
    modId="ctm"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

