name: Bug report
about: Exclusive to issue tracker only.
labels: [bug]
body:
- type: markdown
  attributes:
    value: "If you need help running TNT and Disparity, please visit us on our Discord server: https://discord.gg/hDJCabNEz3"
- type: dropdown
  attributes:
    label: Operating System
    description: If you know this bug occurs on multiple operating systems, select all you have tested.
    multiple: true
    options:
    - Windows
    - macOS
    - Linux
    - Other
- type: textarea
  attributes:
    label: Operating System Version
    description: If you select the bug occuring on multiple operating systems, select what version you tested.
    placeholder: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Mod Version
    description: We need to know what version of TNT and Disparity you used.
    placeholder: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Description of bug
    description: What did you expect to happen, what happened, and why is it incorrect?
    placeholder: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: A bulleted list, or an exported instance if relevant.
    placeholder: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Suspected cause
    description: If you know what could be causing this bug, describe it here.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: This issue is unique
    options:
    - label: I have searched the issue tracker and did not find an issue describing my bug.
      required: true      
