name: Bug report
description: File a bug report
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      ## Use this form if you wan't to report a bug to TNT and Disparity Mod.
      If you need help running TNT and Disparity, please visit us on our Discord server: https://discord.gg/hDJCabNEz3
- type: dropdown
  attributes:
    label: Operating System
    description: If you know this bug occurs on multiple operating systems, select all you have tested.
    multiple: true
    options:
    - Windows
    - macOS
    - Linux
    - Other
  validations:
    required: true
- type: input
  attributes:
    label: Operating System Version
    description: If you select the bug occuring on multiple operating systems, select what version you tested.
    placeholder: 10.0.19041.935
  validations:
    required: true
- type: input
  attributes:
    label: Mod Version
    description: We need to know what version of TNT and Disparity you used.
    placeholder: Alpha 0.4.1 Build 639 Pre-Integration Test
  validations:
    required: true
- type: input
  attributes:
    label: Minecraft Version
    description: We need to know what version of Minecraft you used.
    placeholder: 1.16.5
  validations:
    required: true
- type: textarea
  attributes:
    label: Description of bug
    description: What did you expect to happen, what happened, and why is it incorrect?
    placeholder: When I launch the game it crashed.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: A bulleted list, or an exported instance if relevant.
    placeholder: Launch Minecraft.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suspected cause
    description: If you know what could be causing this bug, describe it here.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Check the following if you have followed.
    options:
    - label: I have searched the issue tracker and did not find an issue describing my bug.
      required: true
    - label: I read the [Code of Conduct](https://github.com/Team-Burnuts/BurnutsPlusTNTandDisparityMod/blob/master/CODE_OF_CONDUCT.md) and pledged to follow it.
      required: true 
