name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      ### Use this form if you wan't to request a feature to TNT and Disparity Mod.
      **Note: Feature Request will be added to a specific milestone before being added to our mod.**
- type: input
  attributes:
    label: Suggestion
    description: What do feature do you want for TNT and Disparity mod?
  validations:
    required: true
- type: input
  attributes:
    label: Benefit
