name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      ## Use this form if you wan't to request a feature to TNT and Disparity Mod.
      **Note: Feature Request will be added to a specific milestone before being added to our mod.**
- type: textarea
  attributes:
    label: Suggestion
    description: What do feature do you want for TNT and Disparity mod?
  validations:
    required: true
- type: textarea
  attributes:
    label: Benefit
    description: Is your/our benefit for this feature request?
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Check the following if you have followed.
    options:
    - label: I have searched the issue tracker and did not find an issue suggesting my idea.
      required: true
    - label: I read the [Code of Conduct](https://github.com/Team-Burnuts/BurnutsPlusTNTandDisparityMod/blob/master/CODE_OF_CONDUCT.md) and pledge to follow it.
      required: true 
