name: Run Minecraft
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: autumnblazey/action-get-mc-jar@v1.0.1
        with:
          mcversion: 1.16.5
      - uses: ValkyrienSkies/Minecraft-Architectury-Testing@v1.7
