name: Security Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      run: git clone https://github.com/Team-Burnuts/BurnutsPlusTNTandDisparityMod
    - uses: djdefi/gitavscan@4
      with:
       full: true
    - uses: crazy-max/ghaction-virustotal@v2.4.1
      with:
       vt_api_key: ${{ secrets.VT_API_KEY }}
       files: ./.github/current.jar
       vt_monitor: true
       update_release_body: true
       github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
