name: Helios Security Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cloning repo
      run: git clone https://github.com/Team-Burnuts/BurnutsPlusTNTandDisparityMod
    - name: Build with Maven
      run: mvn -B package --file https://modmaven.dev/teamtwilight/twilightforest/4.0.546/twilightforest-4.0.546.pom
